/* autogenerated file, DO NOT EDIT! */
#include <zebra.h>

#include "command.h"
#include "linklist.h"

#include "vtysh/vtysh.h"

DEFSH (VTYSH_KEYS, accept_lifetime_day_month_day_month_cmd_vtysh,
	"accept-lifetime HH:MM:SS (1-31) MONTH (1993-2035) HH:MM:SS (1-31) MONTH (1993-2035)",
	"Set accept lifetime of the key\n"
	"Time to start\n"
	"Day of th month to start\n"
	"Month of the year to start\n"
	"Year to start\n"
	"Time to expire\n"
	"Day of th month to expire\n"
	"Month of the year to expire\n"
	"Year to expire\n")

DEFSH (VTYSH_KEYS, accept_lifetime_day_month_month_day_cmd_vtysh,
	"accept-lifetime HH:MM:SS (1-31) MONTH (1993-2035) HH:MM:SS MONTH (1-31) (1993-2035)",
	"Set accept lifetime of the key\n"
	"Time to start\n"
	"Day of th month to start\n"
	"Month of the year to start\n"
	"Year to start\n"
	"Time to expire\n"
	"Month of the year to expire\n"
	"Day of th month to expire\n"
	"Year to expire\n")

DEFSH (VTYSH_KEYS, accept_lifetime_duration_day_month_cmd_vtysh,
	"accept-lifetime HH:MM:SS (1-31) MONTH (1993-2035) duration (1-2147483646)",
	"Set accept lifetime of the key\n"
	"Time to start\n"
	"Day of th month to start\n"
	"Month of the year to start\n"
	"Year to start\n"
	"Duration of the key\n"
	"Duration seconds\n")

DEFSH (VTYSH_KEYS, accept_lifetime_duration_month_day_cmd_vtysh,
	"accept-lifetime HH:MM:SS MONTH (1-31) (1993-2035) duration (1-2147483646)",
	"Set accept lifetime of the key\n"
	"Time to start\n"
	"Month of the year to start\n"
	"Day of th month to start\n"
	"Year to start\n"
	"Duration of the key\n"
	"Duration seconds\n")

DEFSH (VTYSH_KEYS, accept_lifetime_infinite_day_month_cmd_vtysh,
	"accept-lifetime HH:MM:SS (1-31) MONTH (1993-2035) infinite",
	"Set accept lifetime of the key\n"
	"Time to start\n"
	"Day of th month to start\n"
	"Month of the year to start\n"
	"Year to start\n"
	"Never expires\n")

DEFSH (VTYSH_KEYS, accept_lifetime_infinite_month_day_cmd_vtysh,
	"accept-lifetime HH:MM:SS MONTH (1-31) (1993-2035) infinite",
	"Set accept lifetime of the key\n"
	"Time to start\n"
	"Month of the year to start\n"
	"Day of th month to start\n"
	"Year to start\n"
	"Never expires\n")

DEFSH (VTYSH_KEYS, accept_lifetime_month_day_day_month_cmd_vtysh,
	"accept-lifetime HH:MM:SS MONTH (1-31) (1993-2035) HH:MM:SS (1-31) MONTH (1993-2035)",
	"Set accept lifetime of the key\n"
	"Time to start\n"
	"Month of the year to start\n"
	"Day of th month to start\n"
	"Year to start\n"
	"Time to expire\n"
	"Day of th month to expire\n"
	"Month of the year to expire\n"
	"Year to expire\n")

DEFSH (VTYSH_KEYS, accept_lifetime_month_day_month_day_cmd_vtysh,
	"accept-lifetime HH:MM:SS MONTH (1-31) (1993-2035) HH:MM:SS MONTH (1-31) (1993-2035)",
	"Set accept lifetime of the key\n"
	"Time to start\n"
	"Month of the year to start\n"
	"Day of th month to start\n"
	"Year to start\n"
	"Time to expire\n"
	"Month of the year to expire\n"
	"Day of th month to expire\n"
	"Year to expire\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, access_list_cmd_vtysh,
	"access-list ACCESSLIST4_NAME$name [seq (1-4294967295)$seq] <deny|permit>$action <A.B.C.D/M$prefix [exact-match$exact]|any>",
	"Access list entry\n"
	"Access list name\n"
	"Sequence number of an entry\n"
	"Sequence number\n"
	"Specify packets to reject\n"
	"Specify packets to forward\n"
	"Prefix to match. e.g. 10.0.0.0/8\n"
	"Exact match of the prefixes\n"
	"Match any IPv4\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, access_list_ext_cmd_vtysh,
	"access-list ACCESSLIST4_NAME$name [seq (1-4294967295)$seq] <deny|permit>$action ip <A.B.C.D$src A.B.C.D$src_mask|host A.B.C.D$src|any> <A.B.C.D$dst A.B.C.D$dst_mask|host A.B.C.D$dst|any>",
	"Access list entry\n"
	"Access list name\n"
	"Sequence number of an entry\n"
	"Sequence number\n"
	"Specify packets to reject\n"
	"Specify packets to forward\n"
	"IPv4 address\n"
	"Source address to match\n"
	"Source address mask to apply\n"
	"Single source host\n"
	"Source address to match\n"
	"Any source host\n"
	"Destination address to match\n"
	"Destination address mask to apply\n"
	"Single destination host\n"
	"Destination address to match\n"
	"Any destination host\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, access_list_remark_cmd_vtysh,
	"access-list ACCESSLIST4_NAME$name remark LINE...",
	"Access list entry\n"
	"Access list name\n"
	"Access list entry comment\n"
	"Comment up to 100 characters\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, access_list_std_cmd_vtysh,
	"access-list ACCESSLIST4_NAME$name [seq (1-4294967295)$seq] <deny|permit>$action <[host] A.B.C.D$host|A.B.C.D$host A.B.C.D$mask>",
	"Access list entry\n"
	"Access list name\n"
	"Sequence number of an entry\n"
	"Sequence number\n"
	"Specify packets to reject\n"
	"Specify packets to forward\n"
	"A single host address\n"
	"Address to match\n"
	"Address to match\n"
	"Wildcard bits\n")

DEFSH_HIDDEN (VTYSH_BGPD|VTYSH_ISISD|VTYSH_OSPF6D|VTYSH_OSPFD|VTYSH_RIPD|VTYSH_ZEBRA, agentx_enable_cmd_vtysh,
	"agentx",
	"SNMP AgentX protocol settings\n")

DEFSH (VTYSH_KEYS, cryptographic_algorithm_cmd_vtysh,
	"cryptographic-algorithm <md5|hmac-sha-1|hmac-sha-256|hmac-sha-384|hmac-sha-512>$algo",
	"Cryptographic-algorithm\n"
	"Use MD5 algorithm\n"
	"Use HMAC-SHA-1 algorithm\n"
	"Use HMAC-SHA-256 algorithm\n"
	"Use HMAC-SHA-384 algorithm\n"
	"Use HMAC-SHA-512 algorithm\n")

DEFSH (VTYSH_ALL, exec_timeout_min_cmd_vtysh,
	"exec-timeout (0-35791)",
	"Set timeout value\n"
	"Timeout value in minutes\n")

DEFSH (VTYSH_ALL, exec_timeout_sec_cmd_vtysh,
	"exec-timeout (0-35791) (0-2147483)",
	"Set the EXEC timeout\n"
	"Timeout in minutes\n"
	"Timeout in seconds\n")

DEFSH_HIDDEN (VTYSH_ALL, frr_defaults_cmd_vtysh,
	"frr defaults PROFILE...",
	"FRRouting global parameters\n"
	"set of configuration defaults used\n"
	"profile string\n")

DEFSH_HIDDEN (VTYSH_ALL, frr_version_cmd_vtysh,
	"frr version VERSION...",
	"FRRouting global parameters\n"
	"version configuration was written by\n"
	"version string\n")

DEFSH (VTYSH_MGMTD, if_ipv4_route_map_cmd_vtysh,
	"route-map ROUTE-MAP <in$in|out> IFNAME",
	"Route map set\n"
	"Route map name\n"
	"Route map set for input filtering\n"
	"Route map set for output filtering\n"
	"Interface information\n")

DEFSH (VTYSH_MGMTD, if_ipv6_route_map_cmd_vtysh,
	"route-map ROUTE-MAP <in$in|out> IFNAME",
	"Route map set\n"
	"Route map name\n"
	"Route map set for input filtering\n"
	"Route map set for output filtering\n"
	"Interface information\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, ip_prefix_list_cmd_vtysh,
	"ip prefix-list PREFIXLIST4_NAME$name [seq (1-4294967295)$seq] <deny|permit>$action <any|A.B.C.D/M$prefix [{ge (0-32)$ge|le (0-32)$le}]>",
	"IP information\n"
	"Build a prefix list\n"
	"Prefix list entry name\n"
	"Sequence number of an entry\n"
	"Sequence number\n"
	"Specify packets to reject\n"
	"Specify packets to forward\n"
	"Any prefix match.  Same as \"0.0.0.0/0 le 32\"\n"
	"IP prefix <network>/<length>, e.g., 35.0.0.0/8\n"
	"Minimum prefix length to be matched\n"
	"Minimum prefix length\n"
	"Maximum prefix length to be matched\n"
	"Maximum prefix length\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, ip_prefix_list_remark_cmd_vtysh,
	"ip prefix-list PREFIXLIST4_NAME$name description LINE...",
	"IP information\n"
	"Build a prefix list\n"
	"Prefix list entry name\n"
	"Access list entry comment\n"
	"Comment up to 100 characters\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, ipv6_access_list_cmd_vtysh,
	"ipv6 access-list ACCESSLIST6_NAME$name [seq (1-4294967295)$seq] <deny|permit>$action <X:X::X:X/M$prefix [exact-match$exact]|any>",
	"IPv6 information\n"
	"Access list entry\n"
	"Access list name\n"
	"Sequence number of an entry\n"
	"Sequence number\n"
	"Specify packets to reject\n"
	"Specify packets to forward\n"
	"IPv6 prefix\n"
	"Exact match of the prefixes\n"
	"Match any IPv6\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, ipv6_access_list_remark_cmd_vtysh,
	"ipv6 access-list ACCESSLIST6_NAME$name remark LINE...",
	"IPv6 information\n"
	"Access list entry\n"
	"Access list name\n"
	"Access list entry comment\n"
	"Comment up to 100 characters\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, ipv6_prefix_list_cmd_vtysh,
	"ipv6 prefix-list PREFIXLIST6_NAME$name [seq (1-4294967295)] <deny|permit>$action <any|X:X::X:X/M$prefix [{ge (0-128)$ge|le (0-128)$le}]>",
	"IPv6 information\n"
	"Build a prefix list\n"
	"Prefix list entry name\n"
	"Sequence number of an entry\n"
	"Sequence number\n"
	"Specify packets to reject\n"
	"Specify packets to forward\n"
	"Any prefix match.  Same as \"::0/0 le 128\"\n"
	"IPv6 prefix <network>/<length>, e.g., 3ffe::/16\n"
	"Maximum prefix length to be matched\n"
	"Maximum prefix length\n"
	"Minimum prefix length to be matched\n"
	"Minimum prefix length\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, ipv6_prefix_list_remark_cmd_vtysh,
	"ipv6 prefix-list PREFIXLIST6_NAME$name description LINE...",
	"IPv6 information\n"
	"Build a prefix list\n"
	"Prefix list entry name\n"
	"Access list entry comment\n"
	"Comment up to 100 characters\n")

DEFSH (VTYSH_KEYS, key_string_cmd_vtysh,
	"key-string LINE",
	"Set key string\n"
	"The key\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, mac_access_list_cmd_vtysh,
	"mac access-list ACCESSLIST_MAC_NAME$name [seq (1-4294967295)$seq] <deny|permit>$action <X:X:X:X:X:X$mac|any>",
	"MAC address\n"
	"Access list entry\n"
	"Access list name\n"
	"Sequence number of an entry\n"
	"Sequence number\n"
	"Specify packets to reject\n"
	"Specify packets to forward\n"
	"MAC address\n"
	"Match any MAC address\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, mac_access_list_remark_cmd_vtysh,
	"mac access-list ACCESSLIST_MAC_NAME$name remark LINE...",
	"MAC address\n"
	"Access list entry\n"
	"Access list name\n"
	"Access list entry comment\n"
	"Comment up to 100 characters\n")

DEFSH (VTYSH_KEYS, no_accept_lifetime_cmd_vtysh,
	"no accept-lifetime",
	"Negate a command or set its defaults\n"
	"Unset accept-lifetime\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_access_list_all_cmd_vtysh,
	"no access-list ACCESSLIST4_NAME$name",
	"Negate a command or set its defaults\n"
	"Access list entry\n"
	"Access list name\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_access_list_cmd_vtysh,
	"no access-list ACCESSLIST4_NAME$name [seq (1-4294967295)$seq] <deny|permit>$action <A.B.C.D/M$prefix [exact-match$exact]|any>",
	"Negate a command or set its defaults\n"
	"Access list entry\n"
	"Access list name\n"
	"Sequence number of an entry\n"
	"Sequence number\n"
	"Specify packets to reject\n"
	"Specify packets to forward\n"
	"Prefix to match. e.g. 10.0.0.0/8\n"
	"Exact match of the prefixes\n"
	"Match any IPv4\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_access_list_ext_cmd_vtysh,
	"no access-list ACCESSLIST4_NAME$name [seq (1-4294967295)$seq] <deny|permit>$action ip <A.B.C.D$src A.B.C.D$src_mask|host A.B.C.D$src|any> <A.B.C.D$dst A.B.C.D$dst_mask|host A.B.C.D$dst|any>",
	"Negate a command or set its defaults\n"
	"Access list entry\n"
	"Access list name\n"
	"Sequence number of an entry\n"
	"Sequence number\n"
	"Specify packets to reject\n"
	"Specify packets to forward\n"
	"Any Internet Protocol\n"
	"Source address to match\n"
	"Source address mask to apply\n"
	"Single source host\n"
	"Source address to match\n"
	"Any source host\n"
	"Destination address to match\n"
	"Destination address mask to apply\n"
	"Single destination host\n"
	"Destination address to match\n"
	"Any destination host\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_access_list_remark_cmd_vtysh,
	"no access-list ACCESSLIST4_NAME$name remark",
	"Negate a command or set its defaults\n"
	"Access list entry\n"
	"Access list name\n"
	"Access list entry comment\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_access_list_std_cmd_vtysh,
	"no access-list ACCESSLIST4_NAME$name [seq (1-4294967295)$seq] <deny|permit>$action <[host] A.B.C.D$host|A.B.C.D$host A.B.C.D$mask>",
	"Negate a command or set its defaults\n"
	"Access list entry\n"
	"Access list name\n"
	"Sequence number of an entry\n"
	"Sequence number\n"
	"Specify packets to reject\n"
	"Specify packets to forward\n"
	"A single host address\n"
	"Address to match\n"
	"Address to match\n"
	"Wildcard bits\n")

DEFSH_HIDDEN (VTYSH_BGPD|VTYSH_ISISD|VTYSH_OSPF6D|VTYSH_OSPFD|VTYSH_RIPD|VTYSH_ZEBRA, no_agentx_cmd_vtysh,
	"no agentx",
	"Negate a command or set its defaults\n"
	"SNMP AgentX protocol settings\n")

DEFSH (VTYSH_KEYS, no_cryptographic_algorithm_cmd_vtysh,
	"no cryptographic-algorithm [<md5|hmac-sha-1|hmac-sha-256|hmac-sha-384|hmac-sha-512>$algo]",
	"Negate a command or set its defaults\n"
	"Cryptographic-algorithm\n"
	"Use MD5 algorithm\n"
	"Use HMAC-SHA-1 algorithm\n"
	"Use HMAC-SHA-256 algorithm\n"
	"Use HMAC-SHA-384 algorithm\n"
	"Use HMAC-SHA-512 algorithm\n")

DEFSH (VTYSH_ALL, no_exec_timeout_cmd_vtysh,
	"no exec-timeout",
	"Negate a command or set its defaults\n"
	"Set the EXEC timeout\n")

DEFSH (VTYSH_MGMTD, no_if_ipv4_route_map_cmd_vtysh,
	"no route-map [ROUTE-MAP] <in$in|out> IFNAME",
	"Negate a command or set its defaults\n"
	"Route map set\n"
	"Route map name\n"
	"Route map set for input filtering\n"
	"Route map set for output filtering\n"
	"Interface information\n")

DEFSH (VTYSH_MGMTD, no_if_ipv6_route_map_cmd_vtysh,
	"no route-map [ROUTE-MAP] <in$in|out> IFNAME",
	"Negate a command or set its defaults\n"
	"Route map set\n"
	"Route map name\n"
	"Route map set for input filtering\n"
	"Route map set for output filtering\n"
	"Interface information\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_ip_prefix_list_all_cmd_vtysh,
	"no ip prefix-list PREFIXLIST4_NAME$name",
	"Negate a command or set its defaults\n"
	"IP information\n"
	"Build a prefix list\n"
	"Prefix list entry name\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_ip_prefix_list_cmd_vtysh,
	"no ip prefix-list PREFIXLIST4_NAME$name [seq (1-4294967295)$seq] <deny|permit>$action <any|A.B.C.D/M$prefix [{ge (0-32)|le (0-32)}]>",
	"Negate a command or set its defaults\n"
	"IP information\n"
	"Build a prefix list\n"
	"Prefix list entry name\n"
	"Sequence number of an entry\n"
	"Sequence number\n"
	"Specify packets to reject\n"
	"Specify packets to forward\n"
	"Any prefix match.  Same as \"0.0.0.0/0 le 32\"\n"
	"IP prefix <network>/<length>, e.g., 35.0.0.0/8\n"
	"Minimum prefix length to be matched\n"
	"Minimum prefix length\n"
	"Maximum prefix length to be matched\n"
	"Maximum prefix length\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_ip_prefix_list_remark_cmd_vtysh,
	"no ip prefix-list PREFIXLIST4_NAME$name description",
	"Negate a command or set its defaults\n"
	"IP information\n"
	"Build a prefix list\n"
	"Prefix list entry name\n"
	"Access list entry comment\n")

DEFSH (VTYSH_ACL_CONFIG, no_ip_prefix_list_remark_line_cmd_vtysh,
	"no ip prefix-list PREFIXLIST4_NAME$name description LINE...",
	"Negate a command or set its defaults\n"
	"IP information\n"
	"Build a prefix list\n"
	"Prefix list entry name\n"
	"Access list entry comment\n"
	"Comment up to 100 characters\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_ip_prefix_list_seq_cmd_vtysh,
	"no ip prefix-list PREFIXLIST4_NAME$name seq (1-4294967295)$seq",
	"Negate a command or set its defaults\n"
	"IP information\n"
	"Build a prefix list\n"
	"Prefix list entry name\n"
	"Sequence number of an entry\n"
	"Sequence number\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_ipv6_access_list_all_cmd_vtysh,
	"no ipv6 access-list ACCESSLIST6_NAME$name",
	"Negate a command or set its defaults\n"
	"IPv6 information\n"
	"Access list entry\n"
	"Access list name\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_ipv6_access_list_cmd_vtysh,
	"no ipv6 access-list ACCESSLIST6_NAME$name [seq (1-4294967295)$seq] <deny|permit>$action <X:X::X:X/M$prefix [exact-match$exact]|any>",
	"Negate a command or set its defaults\n"
	"IPv6 information\n"
	"Access list entry\n"
	"Access list name\n"
	"Sequence number of an entry\n"
	"Sequence number\n"
	"Specify packets to reject\n"
	"Specify packets to forward\n"
	"IPv6 prefix\n"
	"Exact match of the prefixes\n"
	"Match any IPv6\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_ipv6_access_list_remark_cmd_vtysh,
	"no ipv6 access-list ACCESSLIST6_NAME$name remark",
	"Negate a command or set its defaults\n"
	"IPv6 information\n"
	"Access list entry\n"
	"Access list name\n"
	"Access list entry comment\n")

DEFSH (VTYSH_ACL_CONFIG, no_ipv6_access_list_remark_line_cmd_vtysh,
	"no ipv6 access-list ACCESSLIST6_NAME$name remark LINE...",
	"Negate a command or set its defaults\n"
	"IPv6 information\n"
	"Access list entry\n"
	"Access list name\n"
	"Access list entry comment\n"
	"Comment up to 100 characters\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_ipv6_prefix_list_all_cmd_vtysh,
	"no ipv6 prefix-list PREFIXLIST6_NAME$name",
	"Negate a command or set its defaults\n"
	"IPv6 information\n"
	"Build a prefix list\n"
	"Prefix list entry name\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_ipv6_prefix_list_cmd_vtysh,
	"no ipv6 prefix-list PREFIXLIST6_NAME$name [seq (1-4294967295)$seq] <deny|permit>$action <any|X:X::X:X/M$prefix [{ge (0-128)$ge|le (0-128)$le}]>",
	"Negate a command or set its defaults\n"
	"IPv6 information\n"
	"Build a prefix list\n"
	"Prefix list entry name\n"
	"Sequence number of an entry\n"
	"Sequence number\n"
	"Specify packets to reject\n"
	"Specify packets to forward\n"
	"Any prefix match.  Same as \"::0/0 le 128\"\n"
	"IPv6 prefix <network>/<length>, e.g., 3ffe::/16\n"
	"Maximum prefix length to be matched\n"
	"Maximum prefix length\n"
	"Minimum prefix length to be matched\n"
	"Minimum prefix length\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_ipv6_prefix_list_remark_cmd_vtysh,
	"no ipv6 prefix-list PREFIXLIST6_NAME$name description",
	"Negate a command or set its defaults\n"
	"IPv6 information\n"
	"Build a prefix list\n"
	"Prefix list entry name\n"
	"Access list entry comment\n")

DEFSH (VTYSH_ACL_CONFIG, no_ipv6_prefix_list_remark_line_cmd_vtysh,
	"no ipv6 prefix-list PREFIXLIST6_NAME$name description LINE...",
	"Negate a command or set its defaults\n"
	"IPv6 information\n"
	"Build a prefix list\n"
	"Prefix list entry name\n"
	"Access list entry comment\n"
	"Comment up to 100 characters\n")

DEFSH_HIDDEN (VTYSH_ACL_CONFIG, no_ipv6_prefix_list_seq_cmd_vtysh,
	"no ipv6 prefix-list PREFIXLIST6_NAME$name seq (1-4294967295)$seq",
	"Negate a command or set its defaults\n"
	"IPv6 information\n"
	"Build a prefix list\n"
	"Prefix list entry name\n"
	"Sequence number of an entry\n"
	"Sequence number\n")

DEFSH (VTYSH_KEYS, no_key_cmd_vtysh,
	"no key (0-2147483647)",
	"Negate a command or set its defaults\n"
	"Delete a key\n"
	"Key identifier number\n")

DEFSH (VTYSH_KEYS, no_key_string_cmd_vtysh,
	"no key-string [LINE]",
	"Negate a command or set its defaults\n"
	"Unset key string\n"
	"The key\n")

DEFSH (VTYSH_KEYS, no_send_lifetime_cmd_vtysh,
	"no send-lifetime",
	"Negate a command or set its defaults\n"
	"Unset send-lifetime\n")

DEFSH_HIDDEN (VTYSH_VRF, no_vrf_debug_cmd_vtysh,
	"no debug vrf",
	"Negate a command or set its defaults\n"
	"Debugging functions\n"
	"VRF Debugging\n")

DEFSH (VTYSH_ALL, no_vty_access_class_cmd_vtysh,
	"no access-class [WORD]",
	"Negate a command or set its defaults\n"
	"Filter connections based on an IP access list\n"
	"IP access list\n")

DEFSH (VTYSH_ALL, no_vty_login_cmd_vtysh,
	"no login",
	"Negate a command or set its defaults\n"
	"Enable password checking\n")

DEFSH (VTYSH_KEYS, send_lifetime_day_month_day_month_cmd_vtysh,
	"send-lifetime HH:MM:SS (1-31) MONTH (1993-2035) HH:MM:SS (1-31) MONTH (1993-2035)",
	"Set send lifetime of the key\n"
	"Time to start\n"
	"Day of th month to start\n"
	"Month of the year to start\n"
	"Year to start\n"
	"Time to expire\n"
	"Day of th month to expire\n"
	"Month of the year to expire\n"
	"Year to expire\n")

DEFSH (VTYSH_KEYS, send_lifetime_day_month_month_day_cmd_vtysh,
	"send-lifetime HH:MM:SS (1-31) MONTH (1993-2035) HH:MM:SS MONTH (1-31) (1993-2035)",
	"Set send lifetime of the key\n"
	"Time to start\n"
	"Day of th month to start\n"
	"Month of the year to start\n"
	"Year to start\n"
	"Time to expire\n"
	"Month of the year to expire\n"
	"Day of th month to expire\n"
	"Year to expire\n")

DEFSH (VTYSH_KEYS, send_lifetime_duration_day_month_cmd_vtysh,
	"send-lifetime HH:MM:SS (1-31) MONTH (1993-2035) duration (1-2147483646)",
	"Set send lifetime of the key\n"
	"Time to start\n"
	"Day of th month to start\n"
	"Month of the year to start\n"
	"Year to start\n"
	"Duration of the key\n"
	"Duration seconds\n")

DEFSH (VTYSH_KEYS, send_lifetime_duration_month_day_cmd_vtysh,
	"send-lifetime HH:MM:SS MONTH (1-31) (1993-2035) duration (1-2147483646)",
	"Set send lifetime of the key\n"
	"Time to start\n"
	"Month of the year to start\n"
	"Day of th month to start\n"
	"Year to start\n"
	"Duration of the key\n"
	"Duration seconds\n")

DEFSH (VTYSH_KEYS, send_lifetime_infinite_day_month_cmd_vtysh,
	"send-lifetime HH:MM:SS (1-31) MONTH (1993-2035) infinite",
	"Set send lifetime of the key\n"
	"Time to start\n"
	"Day of th month to start\n"
	"Month of the year to start\n"
	"Year to start\n"
	"Never expires\n")

DEFSH (VTYSH_KEYS, send_lifetime_infinite_month_day_cmd_vtysh,
	"send-lifetime HH:MM:SS MONTH (1-31) (1993-2035) infinite",
	"Set send lifetime of the key\n"
	"Time to start\n"
	"Month of the year to start\n"
	"Day of th month to start\n"
	"Year to start\n"
	"Never expires\n")

DEFSH (VTYSH_KEYS, send_lifetime_month_day_day_month_cmd_vtysh,
	"send-lifetime HH:MM:SS MONTH (1-31) (1993-2035) HH:MM:SS (1-31) MONTH (1993-2035)",
	"Set send lifetime of the key\n"
	"Time to start\n"
	"Month of the year to start\n"
	"Day of th month to start\n"
	"Year to start\n"
	"Time to expire\n"
	"Day of th month to expire\n"
	"Month of the year to expire\n"
	"Year to expire\n")

DEFSH (VTYSH_KEYS, send_lifetime_month_day_month_day_cmd_vtysh,
	"send-lifetime HH:MM:SS MONTH (1-31) (1993-2035) HH:MM:SS MONTH (1-31) (1993-2035)",
	"Set send lifetime of the key\n"
	"Time to start\n"
	"Month of the year to start\n"
	"Day of th month to start\n"
	"Year to start\n"
	"Time to expire\n"
	"Month of the year to expire\n"
	"Day of th month to expire\n"
	"Year to expire\n")

DEFSH_HIDDEN (VTYSH_VRF, vrf_debug_cmd_vtysh,
	"debug vrf",
	"Debugging functions\n"
	"VRF Debugging\n")

DEFSH (VTYSH_ALL, vty_access_class_cmd_vtysh,
	"access-class WORD",
	"Filter connections based on an IP access list\n"
	"IP access list\n")

DEFSH (VTYSH_ALL, vty_login_cmd_vtysh,
	"login",
	"Enable password checking\n")

void vtysh_init_cmd(void)
{
	install_element(CONFIG_NODE, &access_list_cmd_vtysh);
	install_element(CONFIG_NODE, &access_list_ext_cmd_vtysh);
	install_element(CONFIG_NODE, &access_list_remark_cmd_vtysh);
	install_element(CONFIG_NODE, &access_list_std_cmd_vtysh);
	install_element(CONFIG_NODE, &agentx_enable_cmd_vtysh);
	install_element(CONFIG_NODE, &frr_defaults_cmd_vtysh);
	install_element(CONFIG_NODE, &frr_version_cmd_vtysh);
	install_element(CONFIG_NODE, &ip_prefix_list_cmd_vtysh);
	install_element(CONFIG_NODE, &ip_prefix_list_remark_cmd_vtysh);
	install_element(CONFIG_NODE, &ipv6_access_list_cmd_vtysh);
	install_element(CONFIG_NODE, &ipv6_access_list_remark_cmd_vtysh);
	install_element(CONFIG_NODE, &ipv6_prefix_list_cmd_vtysh);
	install_element(CONFIG_NODE, &ipv6_prefix_list_remark_cmd_vtysh);
	install_element(CONFIG_NODE, &mac_access_list_cmd_vtysh);
	install_element(CONFIG_NODE, &mac_access_list_remark_cmd_vtysh);
	install_element(CONFIG_NODE, &no_access_list_all_cmd_vtysh);
	install_element(CONFIG_NODE, &no_access_list_cmd_vtysh);
	install_element(CONFIG_NODE, &no_access_list_ext_cmd_vtysh);
	install_element(CONFIG_NODE, &no_access_list_remark_cmd_vtysh);
	install_element(CONFIG_NODE, &no_access_list_std_cmd_vtysh);
	install_element(CONFIG_NODE, &no_agentx_cmd_vtysh);
	install_element(CONFIG_NODE, &no_ip_prefix_list_all_cmd_vtysh);
	install_element(CONFIG_NODE, &no_ip_prefix_list_cmd_vtysh);
	install_element(CONFIG_NODE, &no_ip_prefix_list_remark_cmd_vtysh);
	install_element(CONFIG_NODE, &no_ip_prefix_list_remark_line_cmd_vtysh);
	install_element(CONFIG_NODE, &no_ip_prefix_list_seq_cmd_vtysh);
	install_element(CONFIG_NODE, &no_ipv6_access_list_all_cmd_vtysh);
	install_element(CONFIG_NODE, &no_ipv6_access_list_cmd_vtysh);
	install_element(CONFIG_NODE, &no_ipv6_access_list_remark_cmd_vtysh);
	install_element(CONFIG_NODE, &no_ipv6_access_list_remark_line_cmd_vtysh);
	install_element(CONFIG_NODE, &no_ipv6_prefix_list_all_cmd_vtysh);
	install_element(CONFIG_NODE, &no_ipv6_prefix_list_cmd_vtysh);
	install_element(CONFIG_NODE, &no_ipv6_prefix_list_remark_cmd_vtysh);
	install_element(CONFIG_NODE, &no_ipv6_prefix_list_remark_line_cmd_vtysh);
	install_element(CONFIG_NODE, &no_ipv6_prefix_list_seq_cmd_vtysh);
	install_element(CONFIG_NODE, &no_vrf_debug_cmd_vtysh);
	install_element(CONFIG_NODE, &vrf_debug_cmd_vtysh);
	install_element(ENABLE_NODE, &no_vrf_debug_cmd_vtysh);
	install_element(ENABLE_NODE, &vrf_debug_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &accept_lifetime_day_month_day_month_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &accept_lifetime_day_month_month_day_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &accept_lifetime_duration_day_month_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &accept_lifetime_duration_month_day_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &accept_lifetime_infinite_day_month_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &accept_lifetime_infinite_month_day_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &accept_lifetime_month_day_day_month_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &accept_lifetime_month_day_month_day_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &cryptographic_algorithm_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &key_string_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &no_accept_lifetime_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &no_cryptographic_algorithm_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &no_key_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &no_key_string_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &no_send_lifetime_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &send_lifetime_day_month_day_month_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &send_lifetime_day_month_month_day_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &send_lifetime_duration_day_month_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &send_lifetime_duration_month_day_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &send_lifetime_infinite_day_month_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &send_lifetime_infinite_month_day_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &send_lifetime_month_day_day_month_cmd_vtysh);
	install_element(KEYCHAIN_KEY_NODE, &send_lifetime_month_day_month_day_cmd_vtysh);
	install_element(KEYCHAIN_NODE, &no_key_cmd_vtysh);
	install_element(RIPNG_NODE, &if_ipv6_route_map_cmd_vtysh);
	install_element(RIPNG_NODE, &no_if_ipv6_route_map_cmd_vtysh);
	install_element(RIP_NODE, &if_ipv4_route_map_cmd_vtysh);
	install_element(RIP_NODE, &no_if_ipv4_route_map_cmd_vtysh);
	install_element(VTY_NODE, &exec_timeout_min_cmd_vtysh);
	install_element(VTY_NODE, &exec_timeout_sec_cmd_vtysh);
	install_element(VTY_NODE, &no_exec_timeout_cmd_vtysh);
	install_element(VTY_NODE, &no_vty_access_class_cmd_vtysh);
	install_element(VTY_NODE, &no_vty_login_cmd_vtysh);
	install_element(VTY_NODE, &vty_access_class_cmd_vtysh);
	install_element(VTY_NODE, &vty_login_cmd_vtysh);
}
